
package web.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import web.service.Mail;
import web.service.MailWSResponse;
import web.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MailService", targetNamespace = "http://service.web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailService {


    /**
     * 
     * @param addMail
     * @return
     *     returns web.service.MailWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/MailService/addMailRequest", output = "http://service.web/MailService/addMailResponse")
    public MailWSResponse addMail(
        @WebParam(name = "addMail", partName = "addMail")
        Mail addMail);

    /**
     * 
     * @param id
     * @return
     *     returns web.service.MailWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/MailService/getMailByIdRequest", output = "http://service.web/MailService/getMailByIdResponse")
    public MailWSResponse getMailById(
        @WebParam(name = "id", partName = "id")
        int id);

    /**
     * 
     * @param subject
     * @return
     *     returns web.service.MailWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/MailService/getMailBySubjectRequest", output = "http://service.web/MailService/getMailBySubjectResponse")
    public MailWSResponse getMailBySubject(
        @WebParam(name = "subject", partName = "subject")
        String subject);

    /**
     * 
     * @param email
     * @return
     *     returns web.service.MailWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/MailService/getMailByEmailRequest", output = "http://service.web/MailService/getMailByEmailResponse")
    public MailWSResponse getMailByEmail(
        @WebParam(name = "email", partName = "email")
        String email);

    /**
     * 
     * @return
     *     returns web.service.MailWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/MailService/getAllMailsRequest", output = "http://service.web/MailService/getAllMailsResponse")
    public MailWSResponse getAllMails();

    /**
     * 
     * @param id
     * @return
     *     returns web.service.MailWSResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.web/MailService/deleteMailRequest", output = "http://service.web/MailService/deleteMailResponse")
    public MailWSResponse deleteMail(
        @WebParam(name = "id", partName = "id")
        int id);

}
